#!/bin/zsh

# install shutter
sudo snap install shutter

# fix edit button
sudo dpkg -i shutter/libgoocanvas3_1.0.0-1_amd64.deb
sudo dpkg -i shutter/libgoocanvas-common_1.0.0-1_all.deb
sudo dpkg -i shutter/libgoo-canvas-perl_0.06-2ubuntu3_amd64.deb

# fix broken
sudo apt --fix-broken install
